AREA PROG3,CODE,READONLY
NUMBER RN 1
NUMONES RN 10
NUMZEROES RN 11
ENTRY
MOV R5,#0x40000000
LDR NUMBER,=0xA
MOV NUMONES,#0
MOV NUMZEROES,#0
LOOP LSRS NUMBER,#1
ADDCS NUMONES,#1
ADDCC NUMZEROES,#1
CMP NUMBER,#0
BNE LOOP
STR NUMONES,[R5]
STR NUMZEROES,[R5,#4]
STOP B STOP
END
