AREA PROG8,CODE,READONLY
DIVIDEND RN 1
DIVISOR RN 2
QUOTIENT RN 3
REMAINDER RN 4
N RN 10
R RN 11
NDR RN 12
ENTRY
LDR R5,=0X40000000
MOV N,#6
MOV R,#3
SUB NDR,N,R
MOV DIVIDEND,N
BL FACT
MOV N,DIVISOR
MOV DIVIDEND,R
BL FACT
MOV R,DIVISOR
MOV DIVIDEND,NDR
BL FACT
MOV DIVIDEND,N
MUL DIVISOR,R,DIVISOR
BL DIV
STR QUOTIENT,[R5]
STOP B STOP
FACT MOV DIVISOR,#1
LOOP2 MUL DIVISOR,DIVIDEND,DIVISOR
SUBS DIVIDEND,DIVIDEND,#1
BNE LOOP2
BX LR
DIV MOV QUOTIENT,#0
LOOP3 SUBS DIVIDEND,DIVIDEND,DIVISOR
ADDPL QUOTIENT,QUOTIENT,#1
BPL LOOP3
ADDMI REMAINDER,DIVIDEND,DIVISOR
BX LR
END
